# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    uses:
      bigbird023/github-actions/.github/workflows/go-build-workflow.yaml@main 
    with:
      TESTCOVERAGE_THRESHOLD: 0
